# Generated by Django 2.1.1 on 2019-04-21 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_id', models.CharField(max_length=31, unique=True)),
                ('factor_number', models.CharField(blank=True, max_length=31)),
                ('card_number', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
